language: node_js
node_js:
  - "8.11.3"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  - CXX=g++-4.8

script:
  - npm run dist

before_deploy:
  - cd dist
  - tar --remove-files -cvzf minemeld-webui-$TRAVIS_TAG.tar.gz *
  - cd ..
  - ls dist

deploy:
  provider: s3
  access_key_id: "$S3_ACCESS_KEY"
  secret_access_key: "$S3_SECRET_ACCESS_KEY"
  bucket: "minemeld"
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  on:
    tags: true

after_deploy:
    - "export FILENAME=minemeld-webui-$TRAVIS_TAG.tar.gz"
    - "export MD5SUM=$(md5sum dist/$FILENAME | awk '{ print $1 }')"
    - "export SHA256SUM=$(sha256sum dist/$FILENAME | awk '{ print $1 }')"
    - "echo $MD5SUM"
    - "echo $SHA256SUM"

